name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - name: Install Dependencies
        run: pnpm install
      - name: Build Site
        run: pnpm run build
      - name: Publish Site
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
